# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"m\n\rStreamMessage\x12&\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.streaming.DataMessageH\x00\x12$\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x15.streaming.AckMessageH\x00\x42\x0e\n\x0cmessage_type\"P\n\x0b\x44\x61taMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\tneeds_ack\x18\x04 \x01(\x08\"/\n\nAckMessage\x12\x0e\n\x06\x61\x63k_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x32\x61\n\x10StreamingService\x12M\n\x13\x42idirectionalStream\x12\x18.streaming.StreamMessage\x1a\x18.streaming.StreamMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMMESSAGE']._serialized_start=30
  _globals['_STREAMMESSAGE']._serialized_end=139
  _globals['_DATAMESSAGE']._serialized_start=141
  _globals['_DATAMESSAGE']._serialized_end=221
  _globals['_ACKMESSAGE']._serialized_start=223
  _globals['_ACKMESSAGE']._serialized_end=270
  _globals['_STREAMINGSERVICE']._serialized_start=272
  _globals['_STREAMINGSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
