# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streaming_pb2 as streaming__pb2


class StreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BidirectionalStream = channel.stream_stream(
                '/streaming.StreamingService/BidirectionalStream',
                request_serializer=streaming__pb2.StreamMessage.SerializeToString,
                response_deserializer=streaming__pb2.StreamMessage.FromString,
                )


class StreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BidirectionalStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=streaming__pb2.StreamMessage.FromString,
                    response_serializer=streaming__pb2.StreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/streaming.StreamingService/BidirectionalStream',
            streaming__pb2.StreamMessage.SerializeToString,
            streaming__pb2.StreamMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
